server:
  port: 8081
spring:
  application:
    name: PURCHASE-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/purchase_service
    username: postgres
    password: root
  kafka:
   producer:
    bootstrap-servers: 127.0.0.1:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   topic:name: wallet_topics

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

################## Redis Config Starts ###################
## Spring-Caching type: Redis
#  cache:
#    type: redis
## Redis config props
#redis-props:
#  host: localhost
#  port: 6379
## Redis cache config props
#  cache-prefix-key: pk-1
## Redis cache-time-to-live: TTL in (minutes)
#  cache-ttl: 5
################## Redis Config Ends #####################

conversionRate: 1
rewardThreshold: 100
customer:
  client:
    uri: http://localhost:8082/api/customer


