server:
  port: 8082

spring:
  application:
    name: CUSTOMER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/customer_service
    username: postgres
    password: root

    kafka:
      consumer:
        bootstrap-servers: 127.0.0.1:9092
        group-id: wallet
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
         spring:
          json:
           trusted:
            packages: com.loyalty.*
      topic:
        name: wallet_topics

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}